### ISSUE TITLE
Suggestion: stop propagation of events to prevent collision with other libraries

### ISSUE THREAD

**Issue by mauron85** [kornelski/slip#45]
Currently all events are propagated through the DOM tree elements.

Using other libraries is complicated, because events collide with each other.
Good example is using https://github.com/mango/slideout together with current version of slip is impossible.

I've made changes to slip to stop propagation of touch/mouse events, so using slip with other libs is possible. Basically, what needs to be done is:

```
ev.stopPropagation();
```

**Comment by carter-thaxton** [comment]
Can you be more specific where you've added this code?  Or just send a pull request?

**Comment by ValYouW** [comment]
@carter-thaxton I have add the same issue, created a PR https://github.com/kornelski/slip/pull/100
Thanks

**Comment by carter-thaxton** [comment]
Merged PR #100 .
