### ISSUE TITLE
Swipe issue in child elements when having an element inside

### ISSUE THREAD

**Issue by gpasuncion** [kornelski/slip#81]
Child elements can be swiped (move sideways) again when another element is inside it even if you call the preventDefault() method in the custom DOM event.

`<ul id="listId">`
  `<li class="demo-no-swipe">`
      `<h3>Some Heading</h3>`
      `<p>Some text</p>`
  `</li>`
`</ul>`

**Comment by carter-thaxton** [comment]
I believe this is fixed by PR #100 (described in issue #45).
