### ISSUE TITLE
how to add a fixed label column

### ISSUE THREAD

**Issue by avidh** [kornelski/slip#95]
Hi,
I want to have 10 items in the sortable list but would like to display a fixed rank number 1 through 10 in front of the list (sort of like fixed column) so that when the user is dragging an item, they can see what the new rank is before dropping the item.

Is there a way to achieve this?
Thanks in advance.

**Comment by pornel** [comment]
You need to figure out CSS layout for this on your own. This library doesn't have any support for columns or anything like that.
